---
version: 2
updates:
  - package-ecosystem: gitsubmodule
    directory: /
    schedule:
      interval: daily
      timezone: Europe/London
      time: "06:00"
    labels:
      - dependencies

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
      timezone: Europe/London
      time: "06:00"
    labels:
      - dependencies
