# Copyright © 2016 Matt Robinson
#
# SPDX-License-Identifier: GPL-3.0-or-later

if("${CPACK_GENERATOR}" STREQUAL "DEB")
    set(CPACK_COMPONENTS_ALL COMMON LINUX DEBIAN)
elseif("${CPACK_GENERATOR}" STREQUAL "TGZ")
    set(CPACK_COMPONENTS_ALL COMMON LINUX ROOTFILES)
elseif("${CPACK_GENERATOR}" MATCHES "WIX|ZIP")
    set(CPACK_COMPONENTS_ALL COMMON WINDOWS ROOTFILES)
else()
    set(CPACK_COMPONENTS_ALL COMMON)
endif()
