#!/bin/sh -e

# Copyright © 2016 Matt Robinson
#
# SPDX-License-Identifier: GPL-3.0-or-later

SCRIPTDIR=$(dirname "$(readlink -f "$0")")

if [ -z "$DEBFULLNAME" ] || [ -z "$DEBEMAIL" ]; then
    echo "DEBFULLNAME and DEBEMAIL should be set before running this script!" >&2
    exit 1
fi

# Set up the temporary folder to build the packages in
BUILDDIR=$(mktemp -d)

# Build the packages
cd "$BUILDDIR"
cmake -DCPACK_PACKAGE_CONTACT="$DEBFULLNAME <$DEBEMAIL>" \
      -DCMAKE_BUILD_TYPE=Release "$SCRIPTDIR/.."
make package

# Lint the built package
lintian --suppress-tags wrong-name-for-changelog-of-native-package -- *.deb

# Fetch the built packages
cp -- *.deb "$SCRIPTDIR"
cp -- *.tar.gz "$SCRIPTDIR"

# Clean up
rm -r "$BUILDDIR"
